# -*- coding: utf-8 -*-
"""APPRECIATION_RATE_CALCULATOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vSsN8NH6pIkDIl-6PcK3e2Mn6IW0qyov
"""

import pandas as pd
import numpy as np

print("="*80)
print("APPRECIATION RATE CALCULATOR & CODE GENERATOR")
print("="*80)

# ============================================================================
# 1. LOAD DATASETS
# ============================================================================

try:
    # Load property data
    property_df = pd.read_csv('plot_price_historical_dataset_.csv')
    print(f"✓ Property data loaded: {property_df.shape}")

    # Load macro data (loaded to ensure consistency, though not strictly used for plot appreciation)
    macro_df = pd.read_csv('pakistan_macroeconomic_indicators_2020_2026.csv')
    print(f"✓ Macro data loaded: {macro_df.shape}")

except FileNotFoundError as e:
    print(f"❌ Error: {e}")
    print("Ensure CSV files are in the current directory.")
    exit()

# ============================================================================
# 2. DATA CLEANING & PREPARATION
# ============================================================================

# Ensure Date is datetime
property_df['Date'] = pd.to_datetime(property_df['Date'])

# Convert Size to Numeric (e.g., "10 Marla" -> 10.0)
def get_numeric_size(size_str):
    try:
        if 'Marla' in str(size_str):
            return float(str(size_str).split()[0])
        elif 'Kanal' in str(size_str):
            return float(str(size_str).split()[0]) * 20
        else:
            return np.nan
    except:
        return np.nan

property_df['Size_Num'] = property_df['Size'].apply(get_numeric_size)

# Drop rows where size conversion failed or price is missing
property_df = property_df.dropna(subset=['Size_Num', 'Price_PKR'])

# Sort by Date to ensure time-series order is correct
property_df = property_df.sort_values('Date')

print(f"✓ Data cleaned. Total records: {len(property_df)}")

# ============================================================================
# 3. CALCULATE APPRECIATION RATES
# ============================================================================

print("\n[1/2] Calculating appreciation rates for each category...")

# Group by the 4 key dimensions
groups = property_df.groupby(['City', 'Society_Project', 'Location_Type', 'Size_Num'])

appreciation_dict = {}
# List to store results for printing
results_list = []

# Define how many months back to look at for the trend (e.g., last 6 years)
TREND_PERIOD = 75

for name, group in groups:
    city, society, loc_type, size = name

    # Calculate monthly percentage change
    group = group.copy()
    group['Monthly_Growth'] = group['Price_PKR'].pct_change()

    # Get the average growth of the most recent X months
    # We use tail() to get only the most recent data points (latest trends)
    recent_growth = group['Monthly_Growth'].tail(min(len(group), TREND_PERIOD))

    if not recent_growth.empty and not recent_growth.isna().all():
        avg_rate = recent_growth.mean()

        # Store in dictionary
        key = (city, society, loc_type, size)
        appreciation_dict[key] = avg_rate

        # Store for display
        results_list.append({
            'City': city,
            'Society': society,
            'Location Type': loc_type,
            'Size (Marla)': size,
            'Avg Monthly Growth': f"{avg_rate*100:.4f}%",
            'Annualized': f"{( (1+avg_rate)**12 - 1 )*100:.2f}%"
        })

# Create a DataFrame for nice viewing
results_df = pd.DataFrame(results_list)

# Display the calculated rates
print(f"\n✓ Calculated rates based on the last {TREND_PERIOD} months of data.")
print("-"*80)
print(results_df.to_string(index=False))
print("-"*80)

# ============================================================================
# 4. GENERATE HARDCODED PYTHON CODE
# ============================================================================

print("\n[2/2] Generating Python Code for Hardcoding...")
print("-"*80)

print("COPY THE CODE BELOW AND PASTE IT INTO YOUR PREDICTION SCRIPT:\n")

print("APPRECIATION_RATES = {")

# Generate the dictionary entries
entries = []
for key, rate in appreciation_dict.items():
    city, society, loc_type, size = key
    # Create a string like: ('Islamabad', 'DHA Islamabad', 'Residential', 10.0): 0.018,
    entry_str = f"    ({repr(city)}, {repr(society)}, {repr(loc_type)}, {size}): {rate:.6f},"
    entries.append(entry_str)

# Print the dictionary
print("\n".join(entries)[:-1].replace("}", "")) # remove last comma
print("}")
print("-"*80)

# Provide a helper function code snippet
print("\nALSO PASTE THIS HELPER FUNCTION INTO YOUR SCRIPT:\n")
print("""
def get_appreciation_rate(city, society, loc_type, size):
    # Fallback logic: Try exact match, then partial match
    key = (city, society, loc_type, size)

    if key in APPRECIATION_RATES:
        return APPRECIATION_RATES[key]

    # Fallback 1: Try ignoring Location Type
    for (c, s, l, sz), rate in APPRECIATION_RATES.items():
        if c == city and s == society and sz == size:
            return rate

    # Fallback 2: Try ignoring Size
    for (c, s, l, sz), rate in APPRECIATION_RATES.items():
        if c == city and s == society and l == loc_type:
            return rate

    # Fallback 3: Global default (18% annual / ~1.5% monthly)
    return 0.015
""")

print("\n" + "="*80)
print("✓ ANALYSIS COMPLETE")
print("="*80)
print(f"1. The table above shows the calculated rates.")
print("2. The 'APPRECIATION_RATES' dictionary code above can be pasted into your script.")
print("3. Call the helper function 'get_appreciation_rate(...)' in your predict function.")
print("="*80)