# -*- coding: utf-8 -*-
"""web_interface_final_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vSsN8NH6pIkDIl-6PcK3e2Mn6IW0qyov
"""

"""
================================================================================
AI MARKET ANALYSIS - WEB INTERFACE (FIXED DROPDOWNS & SUB-CATEGORIES)
================================================================================
"""

from flask import Flask, render_template_string, request, jsonify
import pickle
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pandas as pd
import json
from datetime import datetime
import os
import warnings
warnings.filterwarnings('ignore')

# Initialize Flask app
app = Flask(__name__)

@app.after_request
def add_cors_headers(response):
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Methods'] = 'GET, POST, OPTIONS'
    response.headers['Access-Control-Allow-Headers'] = 'Content-Type, Authorization'
    return response

# ============================================================================
# 1. LOAD TRAINED MODEL & SCALERS
# ============================================================================

MODEL_PATH = os.path.join(os.path.dirname(__file__), 'best_model_xgboost.pkl')

print("Loading trained model and scalers...")
try:
    with open(MODEL_PATH, 'rb') as f:
        model_data = pickle.load(f)

    best_model = model_data['model']
    scaler_X = model_data['scaler_X']
    feature_cols = model_data['feature_cols']
    le_city = model_data['le_city']
    le_status = model_data['le_status']
    le_society = model_data['le_society']

    print(f"✓ Model loaded: {model_data.get('training_date', 'unknown')}")
except Exception as e:
    print(f"Model load error: {str(e)}")
    print("Using dummy data for UI demonstration.")
    # Dummy data for UI testing if model is missing
    best_model = None

# ============================================================================
# 2. APPRECIATION RATES DATASET
# ============================================================================

APPRECIATION_RATES = {
    ('Islamabad', 'Bahria Town Islamabad', 'Commercial', 4.0): 0.013282,
    ('Islamabad', 'Bahria Town Islamabad', 'Commercial', 5.0): 0.015901,
    ('Islamabad', 'Bahria Town Islamabad', 'Commercial', 6.0): 0.013507,
    ('Islamabad', 'Bahria Town Islamabad', 'Commercial', 7.0): 0.013484,
    ('Islamabad', 'Bahria Town Islamabad', 'Commercial', 8.0): 0.014990,
    ('Islamabad', 'Bahria Town Islamabad', 'Commercial', 9.0): 0.013552,
    ('Islamabad', 'Bahria Town Islamabad', 'Commercial', 10.0): 0.014954,
    ('Islamabad', 'Bahria Town Islamabad', 'Commercial', 12.0): 0.014417,
    ('Islamabad', 'Bahria Town Islamabad', 'Commercial', 13.0): 0.013446,
    ('Islamabad', 'Bahria Town Islamabad', 'Commercial', 14.0): 0.014709,
    ('Islamabad', 'Bahria Town Islamabad', 'Commercial', 15.0): 0.013380,
    ('Islamabad', 'Bahria Town Islamabad', 'Commercial', 16.0): 0.014208,
    ('Islamabad', 'Bahria Town Islamabad', 'Commercial', 17.0): 0.013080,
    ('Islamabad', 'Bahria Town Islamabad', 'Commercial', 18.0): 0.016506,
    ('Islamabad', 'Bahria Town Islamabad', 'Commercial', 19.0): 0.015301,
    ('Islamabad', 'Bahria Town Islamabad', 'Commercial', 20.0): 0.011579,
    ('Islamabad', 'Bahria Town Islamabad', 'Residential', 4.0): 0.055484,
    ('Islamabad', 'Bahria Town Islamabad', 'Residential', 5.0): 0.027176,
    ('Islamabad', 'Bahria Town Islamabad', 'Residential', 6.0): 0.055484,
    ('Islamabad', 'Bahria Town Islamabad', 'Residential', 7.0): 0.055484,
    ('Islamabad', 'Bahria Town Islamabad', 'Residential', 8.0): 0.055484,
    ('Islamabad', 'Bahria Town Islamabad', 'Residential', 9.0): 0.055484,
    ('Islamabad', 'Bahria Town Islamabad', 'Residential', 11.0): 0.055484,
    ('Islamabad', 'Bahria Town Islamabad', 'Residential', 12.0): 0.055484,
    ('Islamabad', 'Bahria Town Islamabad', 'Residential', 13.0): 0.055484,
    ('Islamabad', 'Bahria Town Islamabad', 'Residential', 14.0): 0.055484,
    ('Islamabad', 'Bahria Town Islamabad', 'Residential', 15.0): 0.055484,
    ('Islamabad', 'Bahria Town Islamabad', 'Residential', 16.0): 0.055484,
    ('Islamabad', 'Bahria Town Islamabad', 'Residential', 17.0): 0.055484,
    ('Islamabad', 'Bahria Town Islamabad', 'Residential', 18.0): 0.055484,
    ('Islamabad', 'Bahria Town Islamabad', 'Residential', 19.0): 0.055484,
    ('Islamabad', 'Bahria Town Islamabad', 'Residential', 20.0): 0.055484,
    ('Islamabad', 'Capital Smart City', 'Commercial', 4.0): 0.015627,
    ('Islamabad', 'Capital Smart City', 'Commercial', 5.0): 0.014284,
    ('Islamabad', 'Capital Smart City', 'Commercial', 6.0): 0.014383,
    ('Islamabad', 'Capital Smart City', 'Commercial', 7.0): 0.013253,
    ('Islamabad', 'Capital Smart City', 'Commercial', 8.0): 0.014567,
    ('Islamabad', 'Capital Smart City', 'Commercial', 9.0): 0.015328,
    ('Islamabad', 'Capital Smart City', 'Commercial', 10.0): 0.015841,
    ('Islamabad', 'Capital Smart City', 'Commercial', 12.0): 0.014932,
    ('Islamabad', 'Capital Smart City', 'Commercial', 13.0): 0.016603,
    ('Islamabad', 'Capital Smart City', 'Commercial', 14.0): 0.013012,
    ('Islamabad', 'Capital Smart City', 'Commercial', 15.0): 0.012633,
    ('Islamabad', 'Capital Smart City', 'Commercial', 16.0): 0.014455,
    ('Islamabad', 'Capital Smart City', 'Commercial', 17.0): 0.016727,
    ('Islamabad', 'Capital Smart City', 'Commercial', 18.0): 0.013015,
    ('Islamabad', 'Capital Smart City', 'Commercial', 19.0): 0.015766,
    ('Islamabad', 'Capital Smart City', 'Commercial', 20.0): 0.014698,
    ('Islamabad', 'Capital Smart City', 'Residential', 4.0): 0.032101,
    ('Islamabad', 'Capital Smart City', 'Residential', 5.0): 0.015723,
    ('Islamabad', 'Capital Smart City', 'Residential', 6.0): 0.032101,
    ('Islamabad', 'Capital Smart City', 'Residential', 7.0): 0.032101,
    ('Islamabad', 'Capital Smart City', 'Residential', 8.0): 0.032101,
    ('Islamabad', 'Capital Smart City', 'Residential', 9.0): 0.032101,
    ('Islamabad', 'Capital Smart City', 'Residential', 11.0): 0.032101,
    ('Islamabad', 'Capital Smart City', 'Residential', 12.0): 0.032101,
    ('Islamabad', 'Capital Smart City', 'Residential', 13.0): 0.032101,
    ('Islamabad', 'Capital Smart City', 'Residential', 14.0): 0.032101,
    ('Islamabad', 'Capital Smart City', 'Residential', 15.0): 0.032101,
    ('Islamabad', 'Capital Smart City', 'Residential', 16.0): 0.032101,
    ('Islamabad', 'Capital Smart City', 'Residential', 17.0): 0.032101,
    ('Islamabad', 'Capital Smart City', 'Residential', 18.0): 0.032101,
    ('Islamabad', 'Capital Smart City', 'Residential', 19.0): 0.032101,
    ('Islamabad', 'Capital Smart City', 'Residential', 20.0): 0.032101,
    ('Islamabad', 'DHA Islamabad', 'Commercial', 4.0): 0.014232,
    ('Islamabad', 'DHA Islamabad', 'Commercial', 5.0): 0.012254,
    ('Islamabad', 'DHA Islamabad', 'Commercial', 6.0): 0.014398,
    ('Islamabad', 'DHA Islamabad', 'Commercial', 7.0): 0.013708,
    ('Islamabad', 'DHA Islamabad', 'Commercial', 8.0): 0.014072,
    ('Islamabad', 'DHA Islamabad', 'Commercial', 9.0): 0.014649,
    ('Islamabad', 'DHA Islamabad', 'Commercial', 10.0): 0.015107,
    ('Islamabad', 'DHA Islamabad', 'Commercial', 12.0): 0.016184,
    ('Islamabad', 'DHA Islamabad', 'Commercial', 13.0): 0.014635,
    ('Islamabad', 'DHA Islamabad', 'Commercial', 14.0): 0.014947,
    ('Islamabad', 'DHA Islamabad', 'Commercial', 15.0): 0.014121,
    ('Islamabad', 'DHA Islamabad', 'Commercial', 16.0): 0.014456,
    ('Islamabad', 'DHA Islamabad', 'Commercial', 17.0): 0.015349,
    ('Islamabad', 'DHA Islamabad', 'Commercial', 18.0): 0.013286,
    ('Islamabad', 'DHA Islamabad', 'Commercial', 19.0): 0.012670,
    ('Islamabad', 'DHA Islamabad', 'Commercial', 20.0): 0.014884,
    ('Islamabad', 'DHA Islamabad', 'Residential', 4.0): 0.025730,
    ('Islamabad', 'DHA Islamabad', 'Residential', 5.0): 0.022227,
    ('Islamabad', 'DHA Islamabad', 'Residential', 6.0): 0.025730,
    ('Islamabad', 'DHA Islamabad', 'Residential', 7.0): 0.025730,
    ('Islamabad', 'DHA Islamabad', 'Residential', 8.0): 0.025730,
    ('Islamabad', 'DHA Islamabad', 'Residential', 9.0): 0.025730,
    ('Islamabad', 'DHA Islamabad', 'Residential', 10.0): 0.027397,
    ('Islamabad', 'DHA Islamabad', 'Residential', 11.0): 0.025730,
    ('Islamabad', 'DHA Islamabad', 'Residential', 12.0): 0.025730,
    ('Islamabad', 'DHA Islamabad', 'Residential', 13.0): 0.025730,
    ('Islamabad', 'DHA Islamabad', 'Residential', 14.0): 0.025730,
    ('Islamabad', 'DHA Islamabad', 'Residential', 15.0): 0.025730,
    ('Islamabad', 'DHA Islamabad', 'Residential', 16.0): 0.025730,
    ('Islamabad', 'DHA Islamabad', 'Residential', 17.0): 0.025730,
    ('Islamabad', 'DHA Islamabad', 'Residential', 18.0): 0.025730,
    ('Islamabad', 'DHA Islamabad', 'Residential', 19.0): 0.025730,
    ('Islamabad', 'DHA Islamabad', 'Residential', 20.0): 0.025730,
    ('Islamabad', 'Faisal Town', 'Commercial', 4.0): 0.015705,
    ('Islamabad', 'Faisal Town', 'Commercial', 5.0): 0.017099,
    ('Islamabad', 'Faisal Town', 'Commercial', 6.0): 0.013779,
    ('Islamabad', 'Faisal Town', 'Commercial', 7.0): 0.014241,
    ('Islamabad', 'Faisal Town', 'Commercial', 8.0): 0.013530,
    ('Islamabad', 'Faisal Town', 'Commercial', 9.0): 0.015453,
    ('Islamabad', 'Faisal Town', 'Commercial', 10.0): 0.012681,
    ('Islamabad', 'Faisal Town', 'Commercial', 12.0): 0.014345,
    ('Islamabad', 'Faisal Town', 'Commercial', 13.0): 0.015189,
    ('Islamabad', 'Faisal Town', 'Commercial', 14.0): 0.016558,
    ('Islamabad', 'Faisal Town', 'Commercial', 15.0): 0.013100,
    ('Islamabad', 'Faisal Town', 'Commercial', 16.0): 0.014254,
    ('Islamabad', 'Faisal Town', 'Commercial', 17.0): 0.013622,
    ('Islamabad', 'Faisal Town', 'Commercial', 18.0): 0.016864,
    ('Islamabad', 'Faisal Town', 'Commercial', 19.0): 0.012971,
    ('Islamabad', 'Faisal Town', 'Commercial', 20.0): 0.014196,
    ('Islamabad', 'Faisal Town', 'Residential', 4.0): 0.029640,
    ('Islamabad', 'Faisal Town', 'Residential', 5.0): 0.023751,
    ('Islamabad', 'Faisal Town', 'Residential', 6.0): 0.029640,
    ('Islamabad', 'Faisal Town', 'Residential', 7.0): 0.029640,
    ('Islamabad', 'Faisal Town', 'Residential', 8.0): 0.029640,
    ('Islamabad', 'Faisal Town', 'Residential', 9.0): 0.029640,
    ('Islamabad', 'Faisal Town', 'Residential', 10.0): 0.026178,
    ('Islamabad', 'Faisal Town', 'Residential', 11.0): 0.029640,
    ('Islamabad', 'Faisal Town', 'Residential', 12.0): 0.029640,
    ('Islamabad', 'Faisal Town', 'Residential', 13.0): 0.029640,
    ('Islamabad', 'Faisal Town', 'Residential', 14.0): 0.029640,
    ('Islamabad', 'Faisal Town', 'Residential', 15.0): 0.029640,
    ('Islamabad', 'Faisal Town', 'Residential', 16.0): 0.029640,
    ('Islamabad', 'Faisal Town', 'Residential', 17.0): 0.029640,
    ('Islamabad', 'Faisal Town', 'Residential', 18.0): 0.029640,
    ('Islamabad', 'Faisal Town', 'Residential', 19.0): 0.029640,
    ('Islamabad', 'Faisal Town', 'Residential', 20.0): 0.029640,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Commercial', 4.0): 0.014936,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Commercial', 5.0): 0.014893,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Commercial', 6.0): 0.012379,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Commercial', 7.0): 0.015311,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Commercial', 8.0): 0.012622,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Commercial', 9.0): 0.014891,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Commercial', 10.0): 0.014057,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Commercial', 12.0): 0.014653,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Commercial', 13.0): 0.014480,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Commercial', 14.0): 0.014008,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Commercial', 15.0): 0.014953,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Commercial', 16.0): 0.012722,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Commercial', 17.0): 0.014982,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Commercial', 18.0): 0.016293,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Commercial', 19.0): 0.013055,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Commercial', 20.0): 0.013803,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Residential', 4.0): 0.043920,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Residential', 5.0): 0.021512,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Residential', 6.0): 0.043920,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Residential', 7.0): 0.043920,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Residential', 8.0): 0.043920,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Residential', 9.0): 0.043920,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Residential', 11.0): 0.043920,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Residential', 12.0): 0.043920,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Residential', 13.0): 0.043920,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Residential', 14.0): 0.043920,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Residential', 15.0): 0.043920,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Residential', 16.0): 0.043920,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Residential', 17.0): 0.043920,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Residential', 18.0): 0.043920,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Residential', 19.0): 0.043920,
    ('Rawalpindi', 'Bahria Town Rawalpindi', 'Residential', 20.0): 0.043920,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Commercial', 4.0): 0.015386,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Commercial', 5.0): 0.015213,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Commercial', 6.0): 0.013784,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Commercial', 7.0): 0.013291,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Commercial', 8.0): 0.016157,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Commercial', 9.0): 0.013169,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Commercial', 10.0): 0.015458,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Commercial', 12.0): 0.013157,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Commercial', 13.0): 0.015987,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Commercial', 14.0): 0.013104,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Commercial', 15.0): 0.016765,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Commercial', 16.0): 0.013049,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Commercial', 17.0): 0.015957,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Commercial', 18.0): 0.013031,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Commercial', 19.0): 0.014620,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Commercial', 20.0): 0.016013,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Residential', 4.0): 0.054223,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Residential', 5.0): 0.026558,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Residential', 6.0): 0.054223,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Residential', 7.0): 0.054223,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Residential', 8.0): 0.054223,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Residential', 9.0): 0.054223,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Residential', 11.0): 0.054223,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Residential', 12.0): 0.054223,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Residential', 13.0): 0.054223,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Residential', 14.0): 0.054223,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Residential', 15.0): 0.054223,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Residential', 16.0): 0.054223,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Residential', 17.0): 0.054223,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Residential', 18.0): 0.054223,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Residential',19.0): 0.054223,
    ('Rawalpindi', 'DHA Islamabad-Rawalpindi', 'Residential', 20.0): 0.054223,
    ('Rawalpindi', 'Faisal Hills', 'Commercial', 4.0): 0.012788,
    ('Rawalpindi', 'Faisal Hills', 'Commercial', 5.0): 0.017440,
    ('Rawalpindi', 'Faisal Hills', 'Commercial', 6.0): 0.015141,
    ('Rawalpindi', 'Faisal Hills', 'Commercial', 7.0): 0.014170,
    ('Rawalpindi', 'Faisal Hills', 'Commercial', 8.0): 0.015415,
    ('Rawalpindi', 'Faisal Hills', 'Commercial', 9.0): 0.012031,
    ('Rawalpindi', 'Faisal Hills', 'Commercial', 10.0): 0.014996,
    ('Rawalpindi', 'Faisal Hills', 'Commercial', 12.0): 0.013473,
    ('Rawalpindi', 'Faisal Hills', 'Commercial', 13.0): 0.013630,
    ('Rawalpindi', 'Faisal Hills', 'Commercial', 14.0): 0.014989,
    ('Rawalpindi', 'Faisal Hills', 'Commercial', 15.0): 0.014276,
    ('Rawalpindi', 'Faisal Hills', 'Commercial', 16.0): 0.015817,
    ('Rawalpindi', 'Faisal Hills', 'Commercial', 17.0): 0.014137,
    ('Rawalpindi', 'Faisal Hills', 'Commercial', 18.0): 0.014048,
    ('Rawalpindi', 'Faisal Hills', 'Commercial', 19.0): 0.014165,
    ('Rawalpindi', 'Faisal Hills', 'Commercial', 20.0): 0.015417,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 4.0): 0.052709,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 5.0): 0.029075,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 6.0): 0.052709,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 7.0): 0.052709,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 8.0): 0.052709,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 9.0): 0.052709,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 10.0): 0.026138,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 11.0): 0.052709,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 12.0): 0.052709,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 13.0): 0.052709,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 14.0): 0.052709,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 15.0): 0.052709,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 16.0): 0.052709,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 17.0): 0.052709,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 18.0): 0.052709,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 19.0): 0.052709,
    ('Rawalpindi', 'Faisal Hills', 'Residential', 20.0): 0.052709,
    ('Rawalpindi', 'Grace Valley', 'Commercial', 4.0): 0.014563,
    ('Rawalpindi', 'Grace Valley', 'Commercial', 5.0): 0.015155,
    ('Rawalpindi', 'Grace Valley', 'Commercial', 6.0): 0.015794,
    ('Rawalpindi', 'Grace Valley', 'Commercial', 7.0): 0.015711,
    ('Rawalpindi', 'Grace Valley', 'Commercial', 8.0): 0.014908,
    ('Rawalpindi', 'Grace Valley', 'Commercial', 9.0): 0.014505,
    ('Rawalpindi', 'Grace Valley', 'Commercial', 10.0): 0.014763,
    ('Rawalpindi', 'Grace Valley', 'Commercial', 12.0): 0.013007,
    ('Rawalpindi', 'Grace Valley', 'Commercial', 13.0): 0.015668,
    ('Rawalpindi', 'Grace Valley', 'Commercial', 14.0): 0.013249,
    ('Rawalpindi', 'Grace Valley', 'Commercial', 15.0): 0.013277,
    ('Rawalpindi', 'Grace Valley', 'Commercial', 16.0): 0.015537,
    ('Rawalpindi', 'Grace Valley', 'Commercial', 17.0): 0.013789,
    ('Rawalpindi', 'Grace Valley', 'Commercial', 18.0): 0.015414,
    ('Rawalpindi', 'Grace Valley', 'Commercial', 19.0): 0.016260,
    ('Rawalpindi', 'Grace Valley', 'Commercial', 20.0): 0.014601,
    ('Rawalpindi', 'Grace Valley', 'Residential', 4.0): 0.029176,
    ('Rawalpindi', 'Grace Valley', 'Residential', 5.0): 0.025142,
    ('Rawalpindi', 'Grace Valley', 'Residential', 6.0): 0.029176,
    ('Rawalpindi', 'Grace Valley', 'Residential', 7.0): 0.029176,
    ('Rawalpindi', 'Grace Valley', 'Residential', 8.0): 0.029176,
    ('Rawalpindi', 'Grace Valley', 'Residential', 9.0): 0.029176,
    ('Rawalpindi', 'Grace Valley', 'Residential', 10.0): 0.025194,
    ('Rawalpindi', 'Grace Valley', 'Residential', 11.0): 0.029176,
    ('Rawalpindi', 'Grace Valley', 'Residential', 12.0): 0.029176,
    ('Rawalpindi', 'Grace Valley', 'Residential', 13.0): 0.029176,
    ('Rawalpindi', 'Grace Valley', 'Residential', 14.0): 0.029176,
    ('Rawalpindi', 'Grace Valley', 'Residential', 15.0): 0.029176,
    ('Rawalpindi', 'Grace Valley', 'Residential', 16.0): 0.029176,
    ('Rawalpindi', 'Grace Valley', 'Residential', 17.0): 0.029176,
    ('Rawalpindi', 'Grace Valley', 'Residential', 18.0): 0.029176,
    ('Rawalpindi', 'Grace Valley', 'Residential', 19.0): 0.029176,
    ('Rawalpindi', 'Grace Valley', 'Residential', 20.0): 0.029176
}

# ============================================================================
# 3. DATA PREPARATION (Societies & Sectors)
# ============================================================================

# Generate Societies Data dynamically from the Dictionary Keys
unique_societies = sorted(list({key[1] for key in APPRECIATION_RATES.keys()}))
societies_data = {}
for city in ['Islamabad', 'Rawalpindi']:
    societies_in_city = sorted(list({k[1] for k in APPRECIATION_RATES.keys() if k[0] == city}))
    societies_data[city] = societies_in_city

# Generate Sectors Data (Hardcoded mappings)
sectors_data = {
    'DHA Islamabad': ['Phase 1', 'Phase 2', 'Phase 3', 'Phase 4', 'Phase 5'],
    'Bahria Town Islamabad': ['Block A', 'Block B', 'Commoners', 'Block D', 'Overseas Block'],
    'Capital Smart City': ['Overseas Block', 'Block A', 'Square One', 'Executive Block'],
    'Faisal Town': ['F-1', 'F-2', 'F-3', 'Main Boulevard', 'G-1', 'G-2'],
    'Bahria Town Rawalpindi': ['Phase 1', 'Phase 2', 'Phase 3', 'Phase 4', 'Sector Market', 'Overseas'],
    'DHA Islamabad-Rawalpindi': ['Sector Z', 'Saddar', 'Main Commercial', 'Silver Plaza'],
    'Faisal Hills': ['Commercial Zone A', 'High Rise Plaza', 'Sector C'],
    'Grace Valley': ['Main Boulevard', 'Central Commercial', 'Sector 3'],
}
# Filter sectors to only include societies that exist in our appreciation dictionary
sectors_data = {k: v for k, v in sectors_data.items() if k in unique_societies}

# ============================================================================
# 4. HELPER FUNCTIONS & PREDICTION LOGIC
# ============================================================================

def get_appreciation_rate(city, society, location_type, size_numeric):
    key = (city, society, location_type, size_numeric)
    if key in APPRECIATION_RATES:
        return APPRECIATION_RATES[key]

    # Fallback 1: Try ignoring Size
    for (c, s, l, sz), rate in APPRECIATION_RATES.items():
        if c == city and s == society and l == location_type:
            return rate
    # Fallback 2: Try ignoring Location Type
    for (c, s, l, sz), rate in APPRECIATION_RATES.items():
        if c == city and s == society:
            return rate
    # Fallback 3: City average
    city_rates = [r for (c, s, l, sz), r in APPRECIATION_RATES.items() if c == city]
    if city_rates:
        return sum(city_rates) / len(city_rates)
    return 0.01

def predict_price(input_data):
    try:
        if best_model is None:
             # Mock prediction for UI testing if model is missing
            current_price = float(input_data.get('current_price', 5000000))
            return {
                'success': True,
                'current_price': current_price,
                'predicted_price': current_price * 1.15,
                'lower_bound': current_price * 1.10,
                'upper_bound': current_price * 1.20,
                'estimated_return': current_price * 0.15,
                'return_percentage': 15.0,
                'investment_period': input_data.get('investment_period', '12 Months'),
                'confidence': 85,
                'property_details': input_data
            }

        city = input_data.get('city', 'Islamabad')
        location_type = input_data.get('location_type', 'Residential')
        society = input_data.get('society', '')
        block_sector = input_data.get('block_sector', '')
        size = input_data.get('size', '5 Marla')
        investment_period = input_data.get('investment_period', '12 Months')
        current_price = float(input_data.get('current_price', 5000000))

        size_str = str(size).split()[0]
        size_numeric = float(size_str)

        period_map = {f"{i} Months": i for i in range(2, 37)}
        investment_months = period_map.get(investment_period, 12)

        try: city_encoded = int(le_city.transform([city])[0])
        except: city_encoded = 0
        try: status_encoded = int(le_status.transform(['Mostly Developed'])[0])
        except: status_encoded = 1
        try: society_encoded = int(le_society.transform([society])[0])
        except: society_encoded = 0

        appreciation_rate = get_appreciation_rate(city, society, location_type, size_numeric)

        quarters_back = investment_months / 3
        price_lag1 = float(current_price / (1 + appreciation_rate) ** 1)
        price_lag2 = float(current_price / (1 + appreciation_rate) ** 2)
        price_lag3 = float(current_price / (1 + appreciation_rate) ** 3)
        price_ma2 = float((price_lag1 + price_lag2) / 2)
        price_ma3 = float((price_lag1 + price_lag2 + price_lag3) / 3)
        price_change = float((appreciation_rate * 100) * quarters_back)

        policy_rate = 10.5
        inflation = 5.8
        gdp_growth = 3.5
        construction_cost = 450
        exchange_rate = 513
        unemployment = 4.2

        real_rate = float(policy_rate - inflation)
        economic_stress = float(1.0 - gdp_growth)

        features = np.array([
            float(policy_rate), float(inflation), float(gdp_growth),
            float(construction_cost), float(exchange_rate), float(unemployment),
            price_lag1, price_lag2, price_lag3, price_ma2, price_ma3,
            price_change, real_rate, economic_stress,
            float(city_encoded), float(status_encoded), float(society_encoded), float(size_numeric)
        ]).reshape(1, -1)

        features_scaled = scaler_X.transform(features)
        prediction = float(best_model.predict(features_scaled)[0])

        return {
            'success': True,
            'current_price': float(current_price),
            'predicted_price': prediction,
            'lower_bound': float(prediction * 0.90),
            'upper_bound': float(prediction * 1.10),
            'estimated_return': float(prediction - current_price),
            'return_percentage': float(((prediction - current_price) / current_price) * 100),
            'investment_period': investment_period,
            'confidence': 90,
            'property_details': input_data
        }

    except Exception as e:
        import traceback
        traceback.print_exc()
        return {'success': False, 'error': f'Prediction error: {str(e)}'}

# ============================================================================
# 5. HTML TEMPLATE
# ============================================================================

HTML_TEMPLATE = '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Market Analysis</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);
            min-height: 100vh;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            display: flex; align-items: center; justify-content: center; padding: 20px;
        }
        .container { max-width: 900px; width: 100%; }
        .card {
            background: linear-gradient(135deg, #2a3f5f 0%, #3a4f7f 100%);
            border-radius: 16px; padding: 40px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3); color: #fff;
        }
        .header { text-align: center; margin-bottom: 40px; }
        .header h1 {
            font-size: 32px; font-weight: 700; margin-bottom: 10px;
            background: linear-gradient(135deg, #64b5f6 0%, #81c784 100%);
            -webkit-background-clip: text; -webkit-text-fill-color: transparent;
        }
        .header p { font-size: 16px; color: #b0bec5; font-weight: 300; }
        .form-group { margin-bottom: 25px; }
        .form-row { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
        .form-row.full { grid-template-columns: 1fr; }
        @media (max-width: 768px) { .form-row { grid-template-columns: 1fr; } }

        label {
            display: block; font-size: 12px; font-weight: 600;
            text-transform: uppercase; letter-spacing: 1px; color: #90caf9; margin-bottom: 10px;
        }
        input, select {
            width: 100%; padding: 12px 16px;
            border: 2px solid rgba(144, 202, 249, 0.3);
            border-radius: 8px; background: rgba(255, 255, 255, 0.95);
            color: #1a1a1a; font-size: 16px; transition: all 0.3s ease;
        }
        select {
            cursor: pointer; appearance: none;
            background-image: url('data:image/svg+xml;utf8,<svg fill="%231a1a1a" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M7 10l5 5 5-5z"/></svg>');
            background-repeat: no-repeat; background-position: right 10px center; background-size: 24px;
            padding-right: 40px;
        }
        input:focus, select:focus {
            outline: none; border-color: #64b5f6; background: rgba(255, 255, 255, 1);
            box-shadow: 0 0 0 3px rgba(100, 181, 246, 0.2);
        }
        .button-group { display: flex; gap: 15px; margin-top: 35px; }
        .btn {
            flex: 1; padding: 16px 32px; border: none; border-radius: 8px;
            font-size: 16px; font-weight: 600; cursor: pointer; transition: all 0.3s ease;
            text-transform: uppercase; letter-spacing: 1px;
        }
        .btn-predict {
            background: linear-gradient(135deg, #64b5f6 0%, #42a5f5 100%); color: #fff;
        }
        .btn-predict:hover { transform: translateY(-2px); box-shadow: 0 10px 25px rgba(66, 165, 245, 0.4); }
        .btn-clear {
            background: rgba(255, 255, 255, 0.15); color: #90caf9;
            border: 2px solid rgba(144, 202, 249, 0.5);
        }
        .btn-clear:hover { background: rgba(144, 202, 249, 0.25); border-color: #64b5f6; }

        .result {
            background: rgba(255, 255, 255, 0.08); border: 2px solid rgba(100, 181, 246, 0.3);
            border-radius: 12px; padding: 30px; margin-top: 30px; display: none;
        }
        .result.show { display: block; animation: slideIn 0.3s ease; }
        @keyframes slideIn { from { opacity: 0; transform: translateY(-10px); } to { opacity: 1; transform: translateY(0); } }
        .result h2 { font-size: 20px; margin-bottom: 20px; color: #64b5f6; }
        .price-display { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 20px; }
        .price-item {
            background: rgba(100, 181, 246, 0.1); padding: 15px; border-radius: 8px;
            border-left: 4px solid #64b5f6;
        }
        .price-label { font-size: 12px; color: #90caf9; text-transform: uppercase; margin-bottom: 5px; }
        .price-value { font-size: 24px; font-weight: 700; color: #64b5f6; }
        .return-info {
            background: rgba(129, 199, 132, 0.1); padding: 15px; border-radius: 8px;
            border-left: 4px solid #81c784; margin-top: 15px;
        }
        .return-percentage { font-size: 28px; font-weight: 700; color: #81c784; }
        .error {
            background: rgba(244, 67, 54, 0.15); border: 2px solid rgba(244, 67, 54, 0.5);
            color: #ff8a80; padding: 15px; border-radius: 8px; margin-top: 20px; display: none;
        }
        .loading { display: none; text-align: center; }
        .loading.show { display: block; }
        .spinner {
            width: 40px; height: 40px; border: 3px solid rgba(100, 181, 246, 0.3);
            border-top-color: #64b5f6; border-radius: 50%; animation: spin 0.8s linear infinite; margin: 0 auto 15px;
        }
        @keyframes spin { to { transform: rotate(360deg); } }

        .auth-panel {
            display: flex; flex-wrap: wrap; gap: 12px; justify-content: space-between; align-items: center; margin-top: 18px;
        }
        .auth-buttons {
            display: flex; flex-wrap: wrap; gap: 10px;
        }
        .btn-auth {
            border-radius: 999px; border: none; font-weight: 700; padding: 10px 18px; cursor: pointer;
            box-shadow: 0 10px 18px rgba(0, 0, 0, 0.08); transition: transform 0.2s ease, opacity 0.2s ease;
        }
        .btn-auth:hover { transform: translateY(-1px); opacity: 0.95; }
        .btn-google { background: #4285f4; color: #ffffff; }
        .btn-facebook { background: #1877f2; color: #ffffff; }
        .btn-logout {
            background: rgba(255, 255, 255, 0.12); color: #ffffff; border: 1px solid rgba(255,255,255,0.24);
            border-radius: 999px; font-weight: 700; padding: 10px 18px; cursor: pointer;
        }
        .profile-panel { display: none; align-items: center; gap: 14px; }
        .profile-info { text-align: right; }
        .profile-info span { display: block; line-height: 1.2; }
        .protected-notice {
            margin-top: 20px; padding: 16px 18px; border-radius: 14px;
            background: rgba(255, 255, 255, 0.08); border: 1px solid rgba(255,255,255,0.14);
            color: #bbdefb; font-size: 0.95rem;
        }
        .protected-notice.warning { background: rgba(244, 67, 54, 0.08); border-color: rgba(244,67,54,0.2); color: #ffcdd2; }
        .protected-notice.success { background: rgba(76, 175, 80, 0.08); border-color: rgba(76,175,80,0.2); color: #c8e6c9; }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="header">
                <div>
                    <h1>AI Market Analysis</h1>
                    <p>Enter property details for precise price forecasting</p>
                </div>
            </div>

            <form id="predictionForm">
                <div class="form-row">
                    <div class="form-group">
                        <label>CITY</label>
                        <select id="city" name="city" required onchange="updateSocieties()">
                            <option value="Islamabad">Islamabad</option>
                            <option value="Rawalpindi">Rawalpindi</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>LOCATION TYPE</label>
                        <select id="location_type" name="location_type" required>
                            <option value="Residential">Residential</option>
                            <option value="Commercial">Commercial</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label>SOCIETY / PROJECT</label>
                    <select id="society" name="society" required onchange="updateSectors()">
                        <option value="">Select Society</option>
                        <!-- Populated by JS -->
                    </select>
                </div>

                <!-- CHANGED: Now a Select dropdown instead of Text input -->
                <div class="form-group">
                    <label>BLOCK / SECTOR</label>
                    <select id="block_sector" name="block_sector" required>
                        <option value="">Select Block/Sector</option>
                        <!-- Populated by JS as sub-category of Project -->
                    </select>
                </div>

                <div class="form-row">
                    <div class="form-group">
                        <label>SIZE (MARLA)</label>
                        <select id="size" name="size" required>
                            <option value="4 Marla">4 Marla</option>
                            <option value="5 Marla">5 Marla</option>
                            <option value="6 Marla">6 Marla</option>
                            <option value="7 Marla">7 Marla</option>
                            <option value="8 Marla">8 Marla</option>
                            <option value="10 Marla">10 Marla</option>
                            <option value="12 Marla">12 Marla</option>
                            <option value="15 Marla">15 Marla</option>
                            <option value="18 Marla">18 Marla</option>
                            <option value="20 Marla">20 Marla</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>INVESTMENT PERIOD (MONTHS)</label>
                        <select id="investment_period" name="investment_period" required>
                            <!-- Options generated by JS -->
                        </select>
                    </div>
                </div>

                <div class="form-group form-row full">
                    <label>CURRENT MARKET PRICE (PKR)</label>
                    <input type="number" id="current_price" name="current_price"
                           placeholder="e.g. 5500000" min="1000000" max="500000000" required>
                </div>

                <div class="button-group">
                    <button type="submit" class="btn-predict">Generate Prediction</button>
                    <button type="button" class="btn-clear" onclick="clearForm()">Clear</button>
                </div>
            </form>

            <div class="loading" id="loading">
                <div class="spinner"></div>
                <p>Analyzing market data...</p>
            </div>
            <div class="error" id="error"></div>

            <div class="result" id="result">
                <h2>📊 Prediction Result</h2>
                <div class="price-display">
                    <div class="price-item">
                        <div class="price-label">Current Price</div>
                        <div class="price-value" id="currentPrice">—</div>
                    </div>
                    <div class="price-item">
                        <div class="price-label">Predicted Price</div>
                        <div class="price-value" id="predictedPrice">—</div>
                    </div>
                </div>
                <div class="return-info">
                    <div class="price-label">Estimated Return</div>
                    <div class="return-percentage" id="returnPercentage">—</div>
                    <div class="price-label" style="margin-top: 5px;" id="returnAmount">—</div>
                </div>
            </div>
        </div>
    </div>

    <script>
        // 1. INJECT PYTHON DATA INTO JAVASCRIPT
        // This fixes the issue where options were not showing
        var societiesData = {{ societies_data | tojson | safe }};
        var sectorsData = {{ sectors_data | tojson | safe }};

        const AUTH_BACKEND_URL = 'http://localhost:3000';
        const TOKEN_KEY = 'jwt_token';
        const USER_KEY = 'auth_user';
        const PROVIDER_KEY = 'auth_provider';

        function parseJwt(token) {
            try {
                const base64Url = token.split('.')[1];
                const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
                const jsonPayload = decodeURIComponent(atob(base64).split('').map(function(c) {
                    return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
                }).join(''));
                return JSON.parse(jsonPayload);
            } catch (e) {
                return null;
            }
        }

        function isTokenExpired(token) {
            const payload = parseJwt(token);
            return !payload || (payload.exp && Date.now() >= payload.exp * 1000);
        }

        function getStoredToken() {
            return localStorage.getItem(TOKEN_KEY);
        }

        function getStoredUser() {
            try {
                const json = localStorage.getItem(USER_KEY);
                return json ? JSON.parse(json) : null;
            } catch (e) {
                return null;
            }
        }

        function setAuthSession(token, provider) {
            localStorage.setItem(TOKEN_KEY, token);
            localStorage.setItem(PROVIDER_KEY, provider || 'unknown');

            const payload = parseJwt(token);
            const user = payload ? {
                name: payload.name || payload.username || payload.email || 'User',
                email: payload.email || '',
                provider: provider || payload.provider || 'unknown'
            } : {
                name: 'User',
                email: '',
                provider: provider || 'unknown'
            };
            localStorage.setItem(USER_KEY, JSON.stringify(user));
        }

        function clearAuthSession() {
            localStorage.removeItem(TOKEN_KEY);
            localStorage.removeItem(USER_KEY);
            localStorage.removeItem(PROVIDER_KEY);
            updateAuthUI();
        }

        function isAuthenticated() {
            return true;
        }

        function getAuthHeaders() {
            return { 'Content-Type': 'application/json' };
        }

        const API_BASE_URL = window.location.origin === 'null' ? 'http://127.0.0.1:5000' : window.location.origin;

        function showError(message) {
            var error = document.getElementById('error');
            if (!error) {
                console.error('Error container not found', message);
                return;
            }
            error.textContent = message;
            error.classList.add('show');
        }

        function updateAuthUI() {
            // No social login UI is used in this version.
        }

        function logout() {
            // No authentication session management required.
        }

        function clearForm() {
            var form = document.getElementById('predictionForm');
            if (form) {
                form.reset();
            }
            var result = document.getElementById('result');
            if (result) {
                result.classList.remove('show');
            }
            var error = document.getElementById('error');
            if (error) {
                error.classList.remove('show');
            }
            updateSocieties(); // Reset dropdowns
        }

        function hydrateAuthFromCallback() {
            var params = new URLSearchParams(window.location.search);
            var token = params.get('token');
            var provider = params.get('provider');
            var error = params.get('error');

            if (token) {
                setAuthSession(token, provider);
                window.location.replace('/');
                return;
            }

            if (error) {
                showError('Authentication failed: ' + error);
                return;
            }

            showError('Unable to complete authentication.');
        }

        document.addEventListener('DOMContentLoaded', function() {
            updateSocieties();

            var form = document.getElementById('predictionForm');
            if (form) {
                form.addEventListener('submit', async function(e) {
                    e.preventDefault();

                    var formData = new FormData(e.target);
                    var data = Object.fromEntries(formData);

                    document.getElementById('loading').classList.add('show');
                    document.getElementById('error').textContent = '';
                    document.getElementById('error').classList.remove('show');
                    document.getElementById('result').classList.remove('show');

                    try {
                        var response = await fetch(API_BASE_URL + '/predict', {
                            method: 'POST',
                            headers: getAuthHeaders(),
                            body: JSON.stringify(data)
                        });

                        var result = await response.json();
                        document.getElementById('loading').classList.remove('show');

                        if (result.success) {
                            document.getElementById('currentPrice').textContent = 'PKR ' + result.current_price.toLocaleString();
                            document.getElementById('predictedPrice').textContent = 'PKR ' + Math.round(result.predicted_price).toLocaleString();
                            document.getElementById('returnPercentage').textContent = (result.return_percentage > 0 ? '+' : '') + result.return_percentage.toFixed(2) + '%';
                            document.getElementById('returnAmount').textContent = 'PKR ' + Math.round(result.estimated_return).toLocaleString();
                            document.getElementById('result').classList.add('show');
                        } else {
                            showError(result.error || 'Unknown error');
                        }
                    } catch (error) {
                        document.getElementById('loading').classList.remove('show');
                        showError('Error: ' + error.message);
                    }
                });
            }
        });

        // 2. POPULATE INVESTMENT PERIOD (2 to 36 months)
        const periodSelect = document.getElementById('investment_period');
        if (periodSelect) {
            for (let i = 2; i <= 36; i++) {
                const option = document.createElement('option');
                option.value = i + ' Months';
                option.textContent = i + ' Months';
                if ([12, 18, 24, 36].includes(i)) {
                    option.textContent += ' (Recommended)';
                }
                periodSelect.appendChild(option);
            }
        }

        // 3. UPDATE SOCIETIES BASED ON CITY
        function updateSocieties() {
            const city = document.getElementById('city').value;
            const societySelect = document.getElementById('society');

            // Reset Society and Sector
            societySelect.innerHTML = '<option value="">Select Society</option>';
            document.getElementById('block_sector').innerHTML = '<option value="">Select Block/Sector</option>';

            if (societiesData && societiesData[city]) {
                societiesData[city].forEach(function(society) {
                    const option = document.createElement('option');
                    option.value = society;
                    option.textContent = society;
                    societySelect.appendChild(option);
                });
            }
        }

        // 4. UPDATE SECTORS (Sub-category of Project)
        function updateSectors() {
            const society = document.getElementById('society').value;
            const sectorSelect = document.getElementById('block_sector');

            // Reset sectors
            sectorSelect.innerHTML = '<option value="">Select Block/Sector</option>';

            // Only populate if a society is selected and data exists
            if (society && sectorsData && sectorsData[society]) {
                sectorsData[society].forEach(function(sector) {
                    const option = document.createElement('option');
                    option.value = sector;
                    option.textContent = sector;
                    sectorSelect.appendChild(option);
                });
            }
        }

        updateSocieties();
    </script>
</body>
</html>
'''

AUTH_CALLBACK_PAGE = '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authentication Callback</title>
    <style>
        body { background: #091921; color: #eef7ff; font-family: Arial, sans-serif; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; }
        .shell { max-width: 520px; padding: 28px 32px; border-radius: 18px; background: rgba(18, 46, 67, 0.95); box-shadow: 0 24px 60px rgba(0,0,0,0.24); text-align: center; }
        .shell h1 { margin-bottom: 14px; font-size: 1.7rem; }
        .shell p { line-height: 1.6; color: #b8d7ef; margin-bottom: 20px; }
        .loader { width: 54px; height: 54px; border: 6px solid rgba(255,255,255,0.18); border-top-color: #64b5f6; border-radius: 50%; animation: spin 0.8s linear infinite; margin: 0 auto; }
        @keyframes spin { to { transform: rotate(360deg); } }
    </style>
</head>
<body>
    <div class="shell">
        <h1>Processing authentication...</h1>
        <div class="loader"></div>
        <p>If you are not redirected automatically, <a id="continueLink" href="/" style="color:#64b5f6;">click here</a>.</p>
    </div>
    <script>
        function safeStoreAuth(token, provider) {
            try {
                localStorage.setItem('jwt_token', token);
                localStorage.setItem('auth_provider', provider || 'unknown');
                const payload = parseJwt(token);
                const user = payload ? {
                    name: payload.name || payload.username || payload.email || 'User',
                    email: payload.email || '',
                    provider: provider || payload.provider || 'unknown'
                } : { name: 'User', email: '', provider: provider || 'unknown' };
                localStorage.setItem('auth_user', JSON.stringify(user));
            } catch (error) {
                console.error('Unable to store auth token', error);
            }
        }

        function parseJwt(token) {
            try {
                const base64Url = token.split('.')[1];
                const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
                const jsonPayload = decodeURIComponent(atob(base64).split('').map(function(c) {
                    return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
                }).join(''));
                return JSON.parse(jsonPayload);
            } catch (e) {
                return null;
            }
        }

        const params = new URLSearchParams(window.location.search);
        const token = params.get('token');
        const provider = params.get('provider');
        const error = params.get('error');

        if (token) {
            safeStoreAuth(token, provider);
            window.location.replace('/');
        } else if (error) {
            document.querySelector('.shell h1').textContent = 'Authentication failed';
            document.querySelector('.shell p').textContent = 'Error: ' + error + '. Please try signing in again.';
        } else {
            document.querySelector('.shell h1').textContent = 'Missing authentication token';
            document.querySelector('.shell p').textContent = 'Please return to the app and try again.';
        }
    </script>
</body>
</html>
'''

# ============================================================================
# FLASK ROUTES
# ============================================================================

@app.route('/')
def index():
    """Render main page with data injection"""
    return render_template_string(HTML_TEMPLATE, societies_data=societies_data, sectors_data=sectors_data)

@app.route('/auth/callback')
def auth_callback():
    """Render the frontend auth callback page that stores the JWT token."""
    return render_template_string(AUTH_CALLBACK_PAGE)

@app.route('/predict', methods=['POST', 'OPTIONS'])
def predict():
    """Handle prediction request"""
    if request.method == 'OPTIONS':
        return jsonify({'success': True})
    try:
        data = request.get_json()
        print(f"DEBUG: Prediction request received: {data}")
        print(f"DEBUG: best_model is None: {best_model is None}")
        print(f"DEBUG: scaler_X is None: {scaler_X is None}")
        result = predict_price(data)
        print(f"DEBUG: Prediction result: {result}")
        return jsonify(result)
    except Exception as e:
        import traceback
        print(f"ERROR in /predict: {str(e)}")
        traceback.print_exc()
        return jsonify({'success': False, 'error': str(e)})

if __name__ == '__main__':
    print("✓ Starting Flask server on http://localhost:5000")
    app.run(debug=True, host='0.0.0.0', port=5000)